### ISSUE TITLE
Project has too much makefile

### ISSUE THREAD

**Issue by mlms13** [jvalle/mouse-vs-cheese#1]
49.6% seems excessive. Maybe do less makefile.

![too-much-makefile](https://cloud.githubusercontent.com/assets/1105543/12161587/8b996f98-b4b4-11e5-95b0-ed2b79068852.png)

**Comment by jvalle** [comment]
Your concern has been noted, and we're working on it.

**Comment by jvalle** [comment]
Makefile reduced to <10%.  Closing issue.
